### ISSUE TITLE
[Feature Request] Open in a new tab instead of sidebar

### ISSUE THREAD

**Issue by pcause** [Yohh/obsidian-simple-sketch#7]
### What would you like to see?

I would like an option to open the sketch area in a new tab.

### What problem would this feature solve?

Typically the sidebar is smaller than the main tab area.  I'l like more space to draw in and don't want to have to resize the sidebar larger and then back smaller again when done sketching

**Comment by Yohh** [comment]
it will be available at next release (in a few days), with the sketch size set to the entire viewport size, much better.

Thanks for the request.
